app:
  version: 1.0.0

server:
  port: 8080

spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: ${MAGALUSCHEDULING_DATASOURCE_URL:jdbc:mysql://localhost:3307/magaluscheduling}
    username: ${MAGALUSCHEDULING_DATASOURCE_NAME:magaluscheduling}
    password: ${MAGALUSCHEDULING_DATASOURCE_PASSWORD:magaluscheduling}
  jackson:
    default-property-inclusion: non_null

flyway:
  user: ${MAGALUSCHEDULING_DATASOURCE_NAME:magaluscheduling}
  password: ${MAGALUSCHEDULING_DATASOURCE_PASSWORD:magaluscheduling}
  schemas: ${MAGALUSCHEDULING_DATASOURCE_SCHEMA:magaluscheduling}

hibernate:
  globally_quoted_identifiers: true